create extension if not exists pgcrypto;

create table if not exists public.ila_conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  updated_at timestamptz null,
  company_name text null,
  role text null,
  person_name text null,
  mobile text null,
  email text null,
  event_day text null,
  time_window text null,
  meeting_time text null,
  hall text null,
  stand_number text null,
  shared_stand text null,
  country text null,
  linkedin_connected boolean default false,
  linkedin_message_sent_to text null,
  linkedin_message_status text default 'Not contacted',
  linkedin_reply_notes text null,
  company_relevance text null,
  person_decision_proximity text null,
  pain_confirmed text null,
  pain_category text null,
  pilot_possible text null,
  next_step text null,
  notes text null,
  previous_contact text null,
  meeting_outcome text null,
  follow_up_consent boolean null,
  excel_row_number integer null,
  excel_marker text null,
  excel_company text null,
  excel_hq text null,
  excel_ld_contact text null,
  excel_role_on_ld text null,
  excel_replied text null,
  excel_interested text null,
  excel_ila_contact text null,
  excel_ila_contact_role text null,
  excel_meet_at_ila text null,
  excel_do_what text null,
  excel_day text null,
  excel_time text null,
  excel_meet_after_ila text null,
  lead_score integer null,
  lead_status text null,
  suggested_action text null,
  generated_follow_up text null
);

alter table public.ila_conversations
  add column if not exists updated_at timestamptz null,
  add column if not exists event_day text null,
  add column if not exists time_window text null,
  add column if not exists meeting_time text null,
  add column if not exists hall text null,
  add column if not exists stand_number text null,
  add column if not exists shared_stand text null,
  add column if not exists country text null,
  add column if not exists linkedin_connected boolean default false,
  add column if not exists linkedin_message_sent_to text null,
  add column if not exists linkedin_message_status text default 'Not contacted',
  add column if not exists linkedin_reply_notes text null,
  add column if not exists excel_row_number integer null,
  add column if not exists excel_marker text null,
  add column if not exists excel_company text null,
  add column if not exists excel_hq text null,
  add column if not exists excel_ld_contact text null,
  add column if not exists excel_role_on_ld text null,
  add column if not exists excel_replied text null,
  add column if not exists excel_interested text null,
  add column if not exists excel_ila_contact text null,
  add column if not exists excel_ila_contact_role text null,
  add column if not exists excel_meet_at_ila text null,
  add column if not exists excel_do_what text null,
  add column if not exists excel_day text null,
  add column if not exists excel_time text null,
  add column if not exists excel_meet_after_ila text null;
