export type ConversationInput = {
  company_name?: string | null;
  role?: string | null;
  person_name?: string | null;
  mobile?: string | null;
  email?: string | null;
  event_day?: string | null;
  time_window?: string | null;
  meeting_time?: string | null;
  hall?: string | null;
  stand_number?: string | null;
  shared_stand?: string | null;
  country?: string | null;
  linkedin_connected?: boolean | null;
  linkedin_message_sent_to?: string | null;
  linkedin_message_status?: string | null;
  linkedin_reply_notes?: string | null;
  company_relevance?: string | null;
  person_decision_proximity?: string | null;
  pain_confirmed?: string | null;
  pain_category?: string | null;
  pilot_possible?: string | null;
  next_step?: string | null;
  notes?: string | null;
  previous_contact?: string | null;
  meeting_outcome?: string | null;
  follow_up_consent?: boolean | null;
  excel_row_number?: number | string | null;
  excel_marker?: string | null;
  excel_company?: string | null;
  excel_hq?: string | null;
  excel_ld_contact?: string | null;
  excel_role_on_ld?: string | null;
  excel_replied?: string | null;
  excel_interested?: string | null;
  excel_ila_contact?: string | null;
  excel_ila_contact_role?: string | null;
  excel_meet_at_ila?: string | null;
  excel_do_what?: string | null;
  excel_day?: string | null;
  excel_time?: string | null;
  excel_meet_after_ila?: string | null;
};

export type ConversationRecord = ConversationInput & {
  id: string;
  created_at: string;
  updated_at?: string | null;
  lead_score: number | null;
  lead_status: string | null;
  suggested_action: string | null;
  generated_follow_up: string | null;
};
